# 异常

JavaScript 提供了 `try...catch...finally` 结构来处理异常：

- **`try`** 块包含可能引发异常的代码。
- **`catch`** 块用于捕获异常并处理它。你可以在这里访问异常对象并决定如何响应。
- **`finally`** 块无论是否有异常都会执行，通常用于清理资源。



在 JavaScript 中，`catch` 块可以捕获在 `try` 块内抛出的任何异常。



**示例：**

```javascript
try {
    // 可能抛出异常的代码
    let result = 1 / 0;
} catch (error) {
    // 处理异常
    console.error('An error occurred:', error);
} finally {
    // 清理工作
    console.log('This will run no matter what.');
}
```



## 异常抛出

通过 `throw` 语句显式地抛出异常：

```javascript
if (someCondition) {
    throw new Error('Some condition is not met.');
}
```



## 异常冒泡

如果 `catch` 块没有处理异常，或者抛出了新的异常，那么异常将继续向上冒泡，直到被更高层的 `catch` 捕获，否则将终止脚本的执行。

```javascript
try {
    try {
        // 抛出异常
        throw new Error("Inner exception");
    } catch(e) {
        if (e instanceof TypeError) {
            // 这里只捕获 TypeError，所以 Error 会冒泡出去
            console.log("Caught a TypeError");
        } else {
            // 如果不是 TypeError，就重新抛出异常
            throw e;
        }
    }
} catch(e) {
    // 这个外部的 catch 块将会捕获从内部冒泡出来的 Error
    console.log("Caught an exception:", e.message);
}
```



## 异常类型

JavaScript 中的异常可以分为以下几类：

1. **`Error`** - 这是所有错误的基类，它包含了错误的基本信息，如错误信息和堆栈跟踪。
2. **`EvalError`** - 当 `eval()` 函数遇到错误时抛出。
3. **`RangeError`** - 当一个数值超出其合法范围时抛出，例如在循环中迭代次数过多。
4. **`ReferenceError`** - 当尝试访问未定义的变量时抛出。
5. **`SyntaxError`** - 当解析源代码时遇到语法错误时抛出，这类错误通常在代码加载时即被发现。
6. **`TypeError`** - 当操作数的类型不匹配时抛出，例如对 `null` 或 `undefined` 调用方法。
7. **`URIError`** - 当 `encodeURI()` 或 `decodeURI()` 方法的参数非法时抛出。
8. **`AggregateError`** - 在处理一组并行操作的错误时抛出，例如 Promise.all() 失败时。

除了这些内置的异常类型，你还可以创建自己的异常类型，通过扩展 `Error` 类。



### 使用Error对象

根据错误类型，你也许可以用'name'和'message'获取更精炼的信息。

'name'提供了常规的错误类（如 'DOMException' 或 'Error'），而'message'通常提供了一条从错误对象转换成字符串的简明信息。

```javascript

function ErrorTest(){
    let n = new Error;
    n.name = "Type: ErrorTest";
    n.message = "The is ErrorTest Message!";
    throw n;
}

try {
    ErrorTest();
}
catch(n){
    console.log(`Name:    ${n.name}`);
    console.log(`Message: ${n.message}`);
}
```

输出结果：

```
Name:    Type: ErrorTest
Message: The is ErrorTest Message!
```

